version: '3'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3306:3306'
  magento:
    build: .
    # platform: linux/amd64
    image: test-2
    # ports:
    #   - '80:8080'
    #   - '443:8443'
    environment:
    #   # - MAGENTO_HOST=localhost
    #   # - MAGENTO_DATABASE_HOST=mariadb
    #   # - MAGENTO_DATABASE_PORT_NUMBER=3306
    #   # - MAGENTO_DATABASE_USER=bn_magento
    #   # - MAGENTO_DATABASE_NAME=bitnami_magento
    #   # - ELASTICSEARCH_HOST=elasticsearch
    #   # - ELASTICSEARCH_PORT_NUMBER=9200
    #   # # ALLOW_EMPTY_PASSWORD is recommended only for development.
    #   # - ALLOW_EMPTY_PASSWORD=yes
    #   # - WEB_ALIAS_DOMAIN=local.domain.com
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    volumes:
      - ./:/app:cached
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"
    # volumes:
    #   - 'magento_data:/bitnami/magento'
    # depends_on:
    #   - mariadb
    #   - elasticsearch
    restart: always
  elasticsearch:
    platform: linux/amd64
    # image: docker.io/bitnami/elasticsearch:7
    image: elasticsearch:7.0.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - bootstrap.system_call_filter=false
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - http.port=9200
      - transport.host=localhost
      - transport.tcp.port=9300
    volumes:
      - 'elasticsearch2_data:/usr/share/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
#   magento_data:
#     driver: local
  elasticsearch2_data:
    driver: local
